#!/bin/sh -e

if head -1 "$1" | grep -q '^#'; then
    title=$(head -1 "$1" | sed 's/^..//')
fi

convert_links() {
    sed 's/\.md"/.html"/g'
}

add_home() {
    sed 's,<h1,<header class="home"><a href="/">Home</a></header><h1,'
}

add_size() {
    while read line; do
        for pattern in $(echo "$line" | grep -o 'src="[^"]*.jpg"'); do
            file=$(echo "$pattern" | awk -F'"' '{print $2}')
            attrs=$(identify "./$file" | awk '{print $3}' | sed 's/^/width="/;s/x/" height="/;s/$/"/')
            line=$(echo "$line" | sed "s,$pattern,$pattern $attrs,g")
        done

        echo "$line"
    done
}

add_body_class() {
    cat
}

marked() {
    if [ -d "$PROGDIR/node_modules" ]; then
        "$PROGDIR/node_modules/.bin/marked" "$@"
    else
        "$PROGDIR/../.bin/marked" "$@"
    fi
}

if [ "$1" = index.md ]; then
    add_home() {
        cat
    }

    add_body_class() {
        sed 's/<body class="markdown-body">/<body class="markdown-body home">/'
    }
fi

cat "$PROGDIR/head.html" | sed "s/<title>/<title>$title/" | add_body_class
marked "$1" | convert_links | add_home | add_size
cat "foot.html"
cat "$PROGDIR/foot.html"
