#!/bin/sh -e

title=$(head -1 "$1" | sed 's/^# //')

convert_links() {
    sed 's/\.md"/.html"/g'
}

add_size() {
    while read line; do
        for pattern in $(echo "$line" | grep -o 'src="[^"]*.jpg"'); do
            file=$(echo "$pattern" | awk -F'"' '{print $2}')
            attrs=$(identify "dist/$file" | awk '{print $3}' | sed 's/^/width="/;s/x/" height="/;s/$/"/')
            line=$(echo "$line" | sed "s,$pattern,$pattern $attrs,g")
        done

        echo "$line"
    done
}

add_body_class() {
    cat
}

add_date_class() {
    cat
}

marked() {
    ./node_modules/.bin/marked "$@"
}

if [ "$1" = index.md ]; then
    add_body_class() {
        sed 's/<body>/<body class="home">/'
    }
fi

if [[ "$1" = 20* ]]; then
    add_date_class() {
        sed '1,/<p>/s/<p>/<p class="date">/'
    }
fi

cat "head.html" | sed "1,/<title>/s/<title>/<title>$title/" | add_body_class
marked "$1" | add_date_class | convert_links | add_size
cat "foot.html"
